### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by FunkMonkey** [streamich/linkfs#5]
Unfortunately this nice module doesn't work on Windows. [edit] wrong explanations removed [/edit]

[Edit] In the end we just need to change [line 131](https://github.com/streamich/linkfs/blob/master/src/index.ts#L131) to
```js
 const regex = new RegExp('^(' + from.replace(/\\/g, '\\\\') + ')(\\\\|\/|$)');
```

Thanks a lot!

p.s. rewriting from `/` or ` ` (empty string) to some path doesn't work though it would be nice...

**Comment by FunkMonkey** [comment]
Here is a proposal for rewriting from root (e.g. `link(fs, ['/', 'C:\\some\\folder'])`)

```js
import {resolve, sep} from 'path'; // we need the separator, too

// ...

if(filename.indexOf(from) === 0) {
  const rootRegex = /(?:^[a-zA-Z]:\\$)|(?:^\/$)/; // C:\ vs /
  const isRoot = from.match(rootRegex);
  const baseRegex = '^(' + from.replace(/\\/g, '\\\\') + ')';
  if(isRoot){
    const regex = new RegExp(baseRegex);
    filename = filename.replace(regex, () => to + sep);
  } else {
    const regex = new RegExp(baseRegex + '(\\\\|\/|$)');
    filename = filename.replace(regex, (match, p1, p2) => to + p2);
  }  
}
```

**Comment by streamich** [comment]
Thanks for your fixes!

I have copy-pasted them here: https://github.com/streamich/linkfs/pull/6

**Comment by streamich** [comment]
https://github.com/streamich/linkfs/releases

**Comment by FunkMonkey** [comment]
Great, thanks! That was quick. Installed it and everything works. Hope I didn't break anything on Unix-based operating systems...
